kernbench: advance default kernel version used
When trying to run kernbench, e.g., on openSUSE Tumbleweed, using the
config file in configs/, build fails like this:

awk: arch/x86/tools/gen-insn-attr-x86.awk:260: warning: regexp escape sequence `\:' is not a known regexp operator
awk: arch/x86/tools/gen-insn-attr-x86.awk:350: (FILENAME=arch/x86/lib/x86-opcode-map.txt FNR=41) warning: regexp escape
sequence `\&' is not a known regexp operator
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x20): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [scripts/Makefile.host:99: scripts/dtc/dtc] Error 1
make: *** [Makefile:1279: scripts_dtc] Error 2
make: *** Waiting for unfinished jobs....
Command exited with non-zero status 2

That's apparently due to: https://lkml.org/lkml/2020/4/1/1206

Let's therefore move the version a bit forward, as it's only a matter
of time, before the issue will show up in other distros too.

We go for 5.14 as we still want to be able to run the benchmark on
SLE 15 SP5. And such OS can build 5.14, although only with gcc-9.
That's why we're also adding gcc version check, and we're making
sure we install and use a recent enough one.

Signed-off-by: Dario Faggioli <dfaggioli@suse.com>
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>