kernbench and sockperf: add missing dependencies
We need flex and bison for kernbench, or we'll see this:

  LEX     scripts/kconfig/lexer.lex.c
/bin/sh: flex: command not found
make[1]: *** [scripts/Makefile.lib:196: scripts/kconfig/lexer.lex.c]
Error 127
make: *** [Makefile:562: allmodconfig] Error 2

  YACC    scripts/kconfig/parser.tab.h
/bin/sh: bison: command not found
make[1]: *** [scripts/Makefile.lib:210: scripts/kconfig/parser.tab.h]
Error 127
make: *** [Makefile:562: allmodconfig] Error 2

And libelf-devel and libopenssl-devel as well, or we'll see this:

error: Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please
install libelf-dev, libelf-devel or elfutils-libelf-devel
make: *** [Makefile:1148: prepare-objtool] Error 1
make: *** Waiting for unfinished jobs....

And this:

  DESCEND  objtool
  HOSTCC  scripts/sign-file
  HOSTCC  scripts/extract-cert
  HOSTCC  scripts/insert-sys-cert
scripts/sign-file.c:25:10: fatal error: openssl/opensslv.h: No such
file or directory
   25 | #include <openssl/opensslv.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.host:90: scripts/sign-file] Error 1
make[1]: *** Waiting for unfinished jobs....
scripts/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file
or directory
   21 | #include <openssl/bio.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.host:90: scripts/extract-cert] Error 1
make: *** [Makefile:1097: scripts] Error 2
make: *** Waiting for unfinished jobs....

We also need to make sure that gcc-c++ is installed for sockperf.

Signed-off-by: Dario Faggioli <dfaggioli@suse.com>