boostbuild: Remove "hpc-" prefix when setting BOOST_TOOLCHAIN
Otherwise boost won't build because an unknown toolset is requested,
e.g.

hpc.jam: No such file or directory
/abuild/mmtests/work/sources/boostbuild-1_66_0/tools/build/src/build/toolset.jam:43: in toolset.using
ERROR: rule "hpc.init" unknown in module "toolset".

Signed-off-by: Andreas Herrmann <aherrmann@suse.com>
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>