configs: Set CONTAINER_NO_PIDS_LIMIT for several configs
Default pids limit in container environement is set to 2048.

Configurations config-scheduler-forkintensive,
config-scheduler-unbound, config-workload-futexbench,
config-workload-futexwait, and config-workload-sembench-futex
start benchmarks that want to create more processes.
This fails.

For example
* with config-scheduler-forkintensive
    perf: fork(): Resource temporarily unavailable
* with config-scheduler-unbound
    perf: fork(): Resource temporarily unavailable
* with config-workload-futexbench
    # Running 'futex/lock-pi' benchmark:
    perf: pthread_create: Resource temporarily unavailable
* with config-workload-futexwait
    Starting threads 2063/3072 iteration 1/5
        ERROR: Resource temporarily unavailable: pthread_create
* with config-workload-sembench-futex
    pthread_create: Resource temporarily unavailable

dmesg indicates this as well. It contains entries like
    cgroup: fork rejected by pids controller in /machine.slice/libpod-...

Lift the pids limit restriction for those benchmark configurations.

Signed-off-by: Andreas Herrmann <aherrmann@suse.de>
Signed-off-by: Mel Gorman <mgorman@techsingularity.net>